#!/usr/bin/env python

import os
import sys
import argh
import requests

from os import path


def get_formulas():
    data = requests.get("https://api.github.com/users/saltstack-formulas/repos").json()
    formulas = filter(lambda x: x["name"].endswith("-formula"), data)
    return sorted(formulas, key=lambda x: x["name"])


def curdir_parent_path():
    return path.split(path.realpath(path.curdir))[0]


def curdir_name():
    return path.split(path.realpath(path.curdir))[1]


def formulas_location():
    if curdir_name() == "salt":
        return path.join(curdir_parent_path(), "formulas")

    return path.join(path.realpath(path.curdir), "formulas")


def list():
    for i in get_formulas():
        print i["name"].replace("-formula", ""),
        if i["description"] and i["description"].strip():
            print "-", i["description"]
        else:
            print


def install(*names):
    if not names:
        sys.stderr("Give me a list of formulas to install\n")
        sys.exit(1)

    for name in names:
        formulas = get_formulas()
        name = name.replace("-formula", "")
        if name not in [x["name"].replace("-formula", "") for x in formulas]:
            sys.stderr.write("Uknow formula: %s\n" % name)
            sys.exit(1)

        formula = filter(lambda x: x["name"].replace("-formula", "") == name, formulas)[0]

        if not path.exists(formulas_location()):
            os.makedirs(formulas_location())

        destination_path = path.join(formulas_location(), name)
        if not path.exists(destination_path):
            print "Retreive %s ..." % name
            os.system("git clone -q %s %s" % (formula["clone_url"], destination_path))

        source = path.join(formulas_location(), name, name)
        if not path.exists(source):
            source = path.join(formulas_location(), name, name + ".sls")

        if not path.exists(source):
            sys.stderr.write("Error: was expecting to find a %s/ directory or a %s.sls file in %s\n" % (name, name, formula["html_url"]))

        target = path.join(path.curdir, path.split(source)[1])

        if not path.exists(target):
            print "Link %s" % name
            os.symlink(source, target)
        else:
            print "Already installed: %s" % name


def uninstall(*names):
    if not names:
        sys.stderr("Give me a list of formulas to uninstall\n")
        sys.exit(1)

    for name in names:
        target = path.join(path.curdir, name)
        if not path.exists(target):
            target += ".sls"

        if not path.exists(target):
            sys.stderr.write("Error: %s is not installed\n" % name)
            sys.exit(1)

        if not path.islink(target):
            sys.stderr.write("Error: %s is not a symlink, unexpected situation, abort\n" % name)
            sys.exit(1)

        print "Uninstall %s" % name
        os.remove(target)


parser = argh.ArghParser()
parser.add_commands([list, install, uninstall])


if __name__ == '__main__':
    parser.dispatch()
